### ISSUE TITLE
Conflict with Carpet /player spawn command.

### ISSUE THREAD

**Issue by ghost** [Patbox/BoxOfPlaceholders#1]
Hello. I am using Minecraft 1.17.1, latest Carpet and latest LuckPerms. When you enter the command /player Alex spawn, which should spawn a fake player, an error appears in the chat, and an exception appears in the console if you enter the command /carpet superSecretSettings true in advance: https://gist.github.com/FlamingCherry/c7079e326b9afae6480574649f68b7e1

**Comment by Patbox** [comment]
It looks like it's issue on LuckPerms not handling fake players. I will keep this issue for now, but you should report that to them

**Comment by ghost** [comment]
> It looks like it's issue on LuckPerms not handling fake players. I will keep this issue for now, but you should report that to them

I don't like situations like this, when the developers of two different mods throw the blame on each other, but the developers of LuckPerms said that the problem is on the side of BoxOfPlaceholders https://github.com/lucko/LuckPerms/issues/3104#event-5035346949

**Comment by ghost** [comment]
Oh sorry, I closed this issue by accident 🤦‍♂️

**Comment by Patbox** [comment]
I'm going to fix it on my side, but it will still create issues with other mods for sure

**Comment by ghost** [comment]
> I'm going to fix it on my side, but it will still create issues with other mods for sure

  Okay, thank you =)

**Comment by Patbox** [comment]
Fixed in 1.3.2
